# Generated by Django 3.0.3 on 2020-02-29 10:37

from django.db import migrations

def populate_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([ 
        Group(name='manager'), 
        Group(name='developer') 
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_groups),
    ]
