# Generated by Django 3.0.3 on 2020-03-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_auto_20200229_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('T', 'TODO'), ('D', 'DONE')], default='T', max_length=1),
        ),
    ]
