# Generated by Django 3.0.3 on 2020-03-11 11:07

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_auto_20200229_1034'),
        ('task_manager', '0003_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='assign_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 11, 11, 7, 4, 264609)),
        ),
        migrations.AlterField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(to='task_manager.User'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.User'),
        ),
    ]
